chat/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('users.urls','users'),namespace='users')),
    path('chatting/',include(('chatting.urls','chatting'),namespace='chatting')),
]

chatting/urls.py
from django.urls import path,include

from . import views
app_name='chatting'
urlpatterns = [
    path('', views.index, name='index'),
    path('search',views.search,name='sea'),
    path('<str:room_name>/', views.room, name='room'),
]

users/urls.py
from django.urls import path,include

from . import views
app_name='users'
urlpatterns = [
    path('',views.index,name='index'),
    path('', include('django.contrib.auth.urls')),
    path('registration', views.NewUser, name='register'),
    path('log', views.logout_view, name='log'),
]

chatting/models.py
from django.db import models
from uuid import uuid4

from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()



class Chat(models.Model):
    token=models.CharField(max_length=200)
    user1=models.CharField(max_length=200,default='admin')
    user2=models.CharField(max_length=200,default='admin')

class Message(models.Model):
    chat = models.ForeignKey(Chat, default=0, related_name='message',on_delete=models.CASCADE)
    content = models.TextField(default='Hello')
    timestamp = models.DateTimeField(auto_now_add=True)

users/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.

chatting/forms.py
from django import forms

class SearchForm(forms.Form):
    search=forms.CharField(label='username', max_length=100)

users/forms.py
from django import forms
from django.contrib.auth import get_user_model

non_allowed_usernames = ['abc','aaa','123','admin']
# check for unique email & username

User = get_user_model()

class RegisterForm(forms.Form):
    username = forms.CharField()
    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "id": "user-password"
            }
        )
    )
    password2 = forms.CharField(
        label='Confirm Password',
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "id": "user-confirm-password"
            }
        )
    )

    def clean_username(self):
        username = self.cleaned_data.get("username")
        qs = User.objects.filter(username__iexact=username)
        if username in non_allowed_usernames:
            raise forms.ValidationError("This is an invalid username, please pick another.")
        if qs.exists():
            raise forms.ValidationError("This is an invalid username, please pick another.")
        return username
        
    def clean_email(self):
        email = self.cleaned_data.get("email")
        qs = User.objects.filter(email__iexact=email)
        if qs.exists():
            raise forms.ValidationError("This email is already in use.")
        return email



class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
        "class": "form-control"
    }))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "id": "user-password"
            }
        )
    )
    def clean(self):
         data = super().clean()
         username = data.get("username")
         password = data.get("password")

    def clean_username(self):
        username = self.cleaned_data.get("username")
        qs = User.objects.filter(username__iexact=username) # thisIsMyUsername == thisismyusername
        if not qs.exists():
            raise forms.ValidationError("This is an invalid user.")
        if qs.count() != 1:
            raise forms.ValidationError("This is an invalid user.")

        return username

chatting/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from .forms import SearchForm
from django.utils.safestring import mark_safe
import json
from uuid import uuid4
from .models import Chat,Message
# Create your views here.
User = get_user_model()

@login_required
def search(request):

    if request.method != 'POST':
        form=SearchForm()
    else:
        form=SearchForm(data=request.POST)
        try:
            form=form.data.get("search")
            user=User.objects.get(username__iexact=form)
            chats=Chat.objects.all()
            for chat in chats:
                if str(chat.user1)==str(request.user) or str(chat.user2)==str(request.user):
                    if str(chat.user1)==str(user) or str(chat.user2)==str(user):
                        token=chat.token

                        form=SearchForm()
                        return render(request, "search.html",{'form':form,'token':token,'user':user})
            token = uuid4()
            chats.create(token=token,user1=str(request.user),user2=user)
            #room(request,user)
            form=SearchForm()
            return render(request, "search.html",{'form':form,'token':token,'user':user})
            #return render(request,"chat.html",{'room_name':str(user)})
        except:
            return HttpResponse("User Not Found")
    form=SearchForm()
    return render(request, "search.html",{'form':form,'user':' '})

def index(request):
    return render(request, 'index.html')

@login_required
def room(request, room_name):
    chats=Chat.objects.all()
    for chat in chats:
        if str(chat.user1)==str(request.user) or str(chat.user2)==str(request.user):
            return render(request, 'chat.html', {
                'room_name': room_name
            })
    return render(request, "search.html",{'form':form,'token':token,'user':user})

users/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth import authenticate, login
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
from .forms import LoginForm, RegisterForm

def index(request):
    return render(request,"users/base.html")

def NewUser(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('users:index')
    context = {'form': form}
    return render(request, "users/register.html",context)
def logout_view(request):
    logout(request)
    return render(request,"users/base.html")
# Create your views here.

chatting/templates/chat.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
  {% extends "users/base.html" %}
  {% block content %}
  <div>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ room_name|json_script:"room-name" }}
  </div>
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chatting/'
            + roomName
            + '/'
        );
        document.querySelector('#chat-log').value = ''
        chatSocket.onmessage = function(e) {
            var data = JSON.parse(e.data);
            console.log(data)

            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
    {% endblock content %}
</body>

</html>

chatting/templates/index.html
{% extends "users/base.html" %}
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chatting/' + roomName + '/';
        };
    </script>
</body>
</html>

chatting/templates/search.html
{% extends "users/base.html" %}
{% block content %}
<form method="post" action="{% url 'chatting:sea' %}">
  {% csrf_token %}

    {{ form.as_p }}


    <button type='submit'>Search!</button>
</form>
<a href="/chatting/{{token}}/">{{user}}</a>

{% endblock %}

users/templates/users/base.html
<a href="{% url 'users:log' %}">log out</a>

{% if user.is_authenticated %}
<a href="{% url 'chatting:sea' %}">search</a>
Hello, {{ user.username }}.
 {% else %}
     <a href="{% url 'users:login' %}">log in</a>    {% endif %}
{% block content %}{% endblock content %}

users/templates/users/register.html
{% extends "users/base.html" %}
{% block content %}
<form method="post" action="{% url 'users:register' %}">
  {% csrf_token %}

    {{ form.as_p }}


    <button type='submit'>Send data</button>
    <input type="hidden" name="next"
    value="{% url 'users:index' %}" />
</form>
<a href="{% url 'users:login'  %}">Войти</a>
{% endblock %}